### ISSUE TITLE
Despliegue en Vercel

### ISSUE THREAD

**Issue by ALM-Bloom** [ULL-ESIT-DMSI-2425/nextra-alejandro-melian-lemes-alu0101443126#1]
Hola @crguezl ! Ya he desarrollado la práctica 'Introducción a Nextra' y me  encuentro finalizándola realizando el despliegue en Vercel.
Sin embargo, parece que me tiene que autorizar que seleccione el repositorio dentro de la aplicación para añadirlo a Vercel.
He usado la opción 'install only in selected repositories:'.

Un saludo.

**Comment by crguezl** [comment]
Installation Approved
