### ISSUE TITLE
ReFinalización de la Práctica "Introducción a Nextra"

### ISSUE THREAD

**Issue by ALM-Bloom** [ULL-ESIT-DMSI-2425/nextra-alejandro-melian-lemes-alu0101443126#3]
¡Hola @crguezl!

# 🛠️ **Revisión de la práctica y correcciones realizadas**

He revisado la práctica y he añadido todas las correcciones que me solicitó durante las horas de teoría. A continuación, le detallo las modificaciones realizadas:

---

### 📌 **1. Corregido Bleed**
- Tal como me pidió, he implementado un componente **Bleed**.
- El componente ha sido correctamente llamado desde la página **`sopadepollo`**.

---

### 📌 **2. Reimplementado Cards**
- Tras un arduo trabajo, he reimplementado el componente **Cards**.
- Se ha creado un **CSS** específico para su estilo y un archivo **JSX** que es básicamente una reinterpretación del código en su página de **PL** en **TypeScript**.
- Ahora, el componente **Cards** está correctamente llamado en **`sopadezanahoria`**.

---

### 📌 **3. Reinterpretado Expression Evaluation**
- Según lo que mencionó en teoría, **"Expression Evaluation"** se refiere a la interpolación en **JavaScript**.
- He eliminado el componente que había creado previamente y he añadido un ejemplo sencillo directamente en **`sopacebolla`**.

---

### 📌 **4. Implementado File Trees**
- Creé un componente para representar **File Trees**, solucionando un error de interpretación anterior.
- El ejemplo ya está disponible en **`sopacebolla`**.

---

### 📌 **5. Acceso al Frontmatter**
- Implementé el acceso a las variables del **frontmatter** dentro del archivo **`sancocho`**.  
Esto asegura que las variables sean correctamente interpretadas y accesibles.

---

### 📌 **6. Arreglado iframe**
- Solucioné el problema con el uso de **iframe**, que anteriormente no mostraba correctamente el vídeo de **YouTube**.
- Ahora el vídeo es visible y funcional desde la página.

---

### 📌 **7. Uso de CodeExtension**
- Modifiqué un ejemplo de uso de **CodeExtension** para incluir:
  - 🟩 **Remarcación de líneas**.
  - 📋 **Posibilidad de copiar el código**.
  - 📝 **Asignación de un nombre al bloque de código**.

---

### 📌 **8. Importación de Markdown**
- Utilicé la **importación de un archivo Markdown** en el informe de la práctica, mostrando una lista simple que cumple con los requisitos que me mencionó.

---

### 📌 **9. Arreglado UseConfig**
- Creé un componente que utiliza **UseConfig** para mostrar en el **index** (homepage) el pie de página.  
Esto permite que se muestre de manera dinámica y funcional según los datos configurados.

---

## 📝 **Informe disponible**

Todo lo anterior puede visualizarlo directamente desde el **informe de la práctica**, donde cada implementación está descrita con detalle. Le invito a revisarlo para cualquier comentario o ajuste que considere necesario.

---

¡Un saludazo! 😊  
**Ale**

**Comment by crguezl** [comment]
@ALM-1000011 

- Añade al readme un enlace a tu repo de despliegue
- Evidencias de que "Ha hecho un fork the nextra y se ha familiarizado con el concepto de monorepo"

**Comment by ALM-Bloom** [comment]
@crguezl 

He actualizado el README del repositorio de la organización para contener un enlace al repositorio de despliegue en mi cuenta personal.
Además, he realizado un fork de Nextra [aquí](https://github.com/ALM-1000011/nextra_monorepo).
Entiendo, que familiarizarse con el concepto de monorepo es entender la metodología que éste conlleva. Es decir, efectuar todo el desarrollo de un proyecto bajo un mismo repositorio, corríjame en clase si me equivoco.

Un saludo.

**Comment by crguezl** [comment]
@ALM-1000011 Sí. Correcto. Un monorepo permite la publicación de múltiples módulos desde. el mismo repo. Ya lo vemos en clase
