### ISSUE TITLE
Finalización de la práctica 08 "NextAuth"

### ISSUE THREAD

**Issue by ALM-Bloom** [ULL-ESIT-DMSI-2425/nextra-alejandro-melian-lemes-alu0101443126#6]
# Informe Finalizado

**Buenas @crguezl ,**

Habiendo finalizado el informe, le comunico que, **a la espera de sus objeciones claro está**, la práctica ha sido **finalizada**.

---

### Enlaces:
- **[Página del Proyecto](https://nextra-alejandro-melian-lemes-alu0101443126.vercel.app/)**  
- **[Informe Completo](https://nextra-alejandro-melian-lemes-alu0101443126.vercel.app/informeNextAuth)**

---

🎄 **Le deseo unas muy felices fiestas** 🎄  
Nos vemos el **15 de enero** para la **Gran Despedida**. 🎉

---

¡Saludos cordiales!

---

**Comment by crguezl** [comment]
Buen trabajo @ALM-1000011
